import { StyleSheet } from 'react-native';
import COLORS from '../../constants/colors';

const BORDER_RADIUS = 12;

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    padding: 20,
    position: 'relative',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.textPrimary,
    marginBottom: 20,
  },
  categoryItem: {
    backgroundColor: COLORS.inputBackground,
    padding: 14,
    borderRadius: BORDER_RADIUS,
    marginBottom: 10,
  },
  categoryText: {
    fontSize: 16,
    color: COLORS.textPrimary,
  },
  emptyText: {
    color: COLORS.textSecondary,
    fontStyle: 'italic',
    textAlign: 'center',
    marginTop: 40,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  editRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  editInput: {
    flex: 1,
    backgroundColor: COLORS.inputBackground,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: BORDER_RADIUS,
    paddingHorizontal: 10,
    paddingVertical: 8,
    color: COLORS.textPrimary,
    marginRight: 10,
  },
  confirmButton: {
    backgroundColor: COLORS.success,
    padding: 10,
    borderRadius: 8,
    marginRight: 6,
  },
  cancelButton: {
    backgroundColor: COLORS.danger,
    padding: 10,
    borderRadius: 8,
  },
  colorDot: (color) => ({
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: color,
    marginRight: 10,
  }),
  colorPickerRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 16,
    flexWrap: 'wrap',
  },
  colorCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    margin: 6,
    borderWidth: 2,
    borderColor: '#fff',
    elevation: 2,
  },
  fabBottomRight: {
    position: 'absolute',
    right: 20,
    backgroundColor: COLORS.primary,
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    zIndex: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: BORDER_RADIUS,
    padding: 24,
    width: '100%',
    maxWidth: 400,
    elevation: 10,
    position: 'relative',
  },
  modalClose: {
    position: 'absolute',
    top: 12,
    right: 12,
    padding: 6,
    zIndex: 2,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.textPrimary,
    marginBottom: 20,
    textAlign: 'center',
  },
  modalInput: {
    backgroundColor: COLORS.inputBackground,
    borderColor: COLORS.border,
    borderWidth: 1,
    borderRadius: BORDER_RADIUS,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: COLORS.textPrimary,
  },
  createButton: {
    backgroundColor: COLORS.primary,
    marginTop: 20,
    borderRadius: BORDER_RADIUS,
    paddingVertical: 14,
    alignItems: 'center',
  },
  createButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
});
